/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5.prograll;

import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class Guia2 extends javax.swing.JFrame {

    /**
     * Creates new form Guia2
     */
    public Guia2() {
        initComponents();
        txtIngresar.requestFocus();
        txtAreaMostrar.setEditable(false);
        btnMostrar.setEnabled(false);
        btnOrdenar.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresarDatos = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblDato = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        txtIngresar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMostrar = new javax.swing.JTextArea();
        btnReinicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarDatos.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnIngresarDatos.setText("Ingresar Datos");
        btnIngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        btnOrdenar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnOrdenar.setText("Ordenar Datos");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        btnMostrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnMostrar.setText("Mostrar Datos");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 125, -1));

        btnSalir.setBackground(new java.awt.Color(51, 255, 0));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(0, 255, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        lblDato.setBackground(new java.awt.Color(255, 255, 255));
        lblDato.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblDato.setForeground(new java.awt.Color(255, 255, 255));
        lblDato.setText("Dato 1 ");
        getContentPane().add(lblDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome, Sigfrido.");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        txtIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIngresarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIngresarKeyTyped(evt);
            }
        });
        getContentPane().add(txtIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 80, -1));

        txtAreaMostrar.setColumns(20);
        txtAreaMostrar.setRows(5);
        jScrollPane1.setViewportView(txtAreaMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 150, 170));

        btnReinicio.setText("Reiniciar");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnReinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Programación-Informática.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int cont = 0;
    String dato3 = "";
    String Vector[] = new String[10];
    private void btnIngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDatosActionPerformed
        if (txtIngresar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un dato antes de presionar");
        } else {
            txtIngresar.requestFocus();
            if (cont < 10) {
                txtIngresar.setEnabled(true);
                cont = cont + 1;
                dato3 = txtIngresar.getText().toUpperCase();
                Vector[(cont - 1)] = dato3;
                txtIngresar.setText("");
                if (cont < 10) {
                    lblDato.setText("Dato " + (cont + 1));
                }
                if (cont==10) {
                txtIngresar.setEnabled(false);
                txtIngresar.setText("");
                btnIngresarDatos.setEnabled(false);
                btnMostrar.setEnabled(true);
                btnOrdenar.setEnabled(true);
            }
            } 

            
        }

    }//GEN-LAST:event_btnIngresarDatosActionPerformed

    private void txtIngresarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyTyped
        char dato = evt.getKeyChar();
        String tamanio = txtIngresar.getText();

        if ((dato < 65 || dato > 90) && (dato < 97 || dato > 122) || (tamanio.length() >= 1)) {
            evt.consume();

        }


    }//GEN-LAST:event_txtIngresarKeyTyped

    private void txtIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIngresarKeyPressed
        if (evt.getKeyCode() == 10) {
            btnIngresarDatosActionPerformed(null);
        }

    }//GEN-LAST:event_txtIngresarKeyPressed
    String burbuja = "";
    char dato1 = ' ';
    char dato2 = ' ';
    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
       txtAreaMostrar.setText("");
       Impresion="";
        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {

                dato1 = Vector[j].charAt(0);
                dato2 = Vector[j + 1].charAt(0);
                if (dato1 > dato2) {
                    burbuja = Vector[j];
                    Vector[j] = Vector[j + 1];
                    Vector[j + 1] = burbuja;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Ordenado con Exito");

    }//GEN-LAST:event_btnOrdenarActionPerformed
    String Impresion = "";
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        for (int i = 0; i < 10; i++) {
            Impresion = Impresion + Vector[i] + "\n";
        }
        txtAreaMostrar.setText(Impresion);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
        Opciones op=new Opciones();
        op.setVisible(true);
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        Impresion="";
        txtIngresar.setEnabled(true);
        txtIngresar.requestFocus();
        txtAreaMostrar.setText("");
        btnMostrar.setEnabled(false);
        btnOrdenar.setEnabled(false);
        lblDato.setText("Dato 1");
        btnIngresarDatos.setEnabled(true);
        cont=0;
    }//GEN-LAST:event_btnReinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guia2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarDatos;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDato;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextArea txtAreaMostrar;
    private javax.swing.JTextField txtIngresar;
    // End of variables declaration//GEN-END:variables
}
