/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia5.prograll;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class Guia1 extends javax.swing.JFrame {

    public Guia1() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtArea.setEnabled(false);
        txtDiagonal.setEnabled(false);
        txtResultadoPeri.setEnabled(false);
        txtResulVolu.setEnabled(false);
        txtVolumenCu.setEnabled(false);
        txtPromediado.setEditable(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitGuia1 = new javax.swing.JLabel();
        lblBase = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        lblDiagonal = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtDiagonal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        txtDiametro = new javax.swing.JTextField();
        txtResultadoPeri = new javax.swing.JTextField();
        btnPermietro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblResultadoPeri = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDiagonalCu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVolumenCu = new javax.swing.JTextField();
        btnCalcularCubo = new javax.swing.JButton();
        lblVolumenCubo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        txtDatos = new javax.swing.JTextField();
        btnPromedio = new javax.swing.JButton();
        txtPromediado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar3 = new javax.swing.JButton();
        btnRegresar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        lblEsfera = new javax.swing.JLabel();
        txtRadio2 = new javax.swing.JTextField();
        txtDiametro2 = new javax.swing.JTextField();
        txtResulVolu = new javax.swing.JTextField();
        btnVolumen = new javax.swing.JButton();
        lblRadio2 = new javax.swing.JLabel();
        lblDiametro2 = new javax.swing.JLabel();
        lblResultaVolu = new javax.swing.JLabel();
        btnLimpiar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lblTitGuia1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblTitGuia1.setText("Area y Diagonal");

        lblBase.setText("Base");

        lblAltura.setText("Altura");

        txtBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseActionPerformed(evt);
            }
        });
        txtBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBaseKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBaseKeyTyped(evt);
            }
        });

        txtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlturaKeyTyped(evt);
            }
        });

        lblArea.setText("Area");

        lblDiagonal.setText("Diagonal");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblTitGuia1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDiagonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblBase, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBase)
                            .addComponent(txtAltura)
                            .addComponent(txtArea)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDiagonal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitGuia1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBase)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArea))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiagonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagonal))
                .addGap(38, 38, 38))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Perimetro");

        txtRadio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRadioFocusGained(evt);
            }
        });
        txtRadio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRadioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRadioKeyTyped(evt);
            }
        });

        txtDiametro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiametroFocusGained(evt);
            }
        });
        txtDiametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiametroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametroKeyTyped(evt);
            }
        });

        btnPermietro.setText("Calcular");
        btnPermietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermietroActionPerformed(evt);
            }
        });

        jLabel2.setText("Radio");

        jLabel3.setText("Diametro");

        lblResultadoPeri.setText("Perimetro:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblResultadoPeri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPermietro)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(20, 20, 20)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                        .addComponent(txtDiametro)))
                                .addComponent(txtResultadoPeri)))
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnPermietro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultadoPeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoPeri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 51));

        jLabel4.setText("Diagonal");

        txtDiagonalCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiagonalCuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiagonalCuKeyTyped(evt);
            }
        });

        jLabel5.setText("Volumen");

        btnCalcularCubo.setText("Calcular");
        btnCalcularCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCuboActionPerformed(evt);
            }
        });

        lblVolumenCubo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblVolumenCubo.setText("Volumen Cubo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVolumenCubo)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVolumenCu, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtDiagonalCu))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btnCalcularCubo)
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVolumenCubo)
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiagonalCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVolumenCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnCalcularCubo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Promedio");

        lblPromedio.setText("Dato 1");

        txtDatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDatosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDatosKeyTyped(evt);
            }
        });

        btnPromedio.setText("Ingresar");
        btnPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromedioActionPerformed(evt);
            }
        });

        jLabel8.setText("Promedio");

        btnLimpiar3.setText("Limpiar");
        btnLimpiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnPromedio)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(lblPromedio)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPromediado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPromedio)
                    .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPromedio)
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPromediado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnLimpiar3)
                .addContainerGap())
        );

        btnRegresar1.setText("Regresar");
        btnRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresar1ActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        lblEsfera.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lblEsfera.setText("Volumen Esfera");

        txtRadio2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRadio2FocusGained(evt);
            }
        });
        txtRadio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRadio2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRadio2KeyTyped(evt);
            }
        });

        txtDiametro2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiametro2FocusGained(evt);
            }
        });
        txtDiametro2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiametro2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametro2KeyTyped(evt);
            }
        });

        btnVolumen.setText("Calcular");
        btnVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumenActionPerformed(evt);
            }
        });

        lblRadio2.setText("Radio");

        lblDiametro2.setText("Diametro");

        lblResultaVolu.setText("Volumen");

        btnLimpiar2.setText("Limpiar");
        btnLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblResultaVolu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiar2)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnVolumen)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addComponent(lblDiametro2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addComponent(lblRadio2)
                                            .addGap(20, 20, 20)))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRadio2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                        .addComponent(txtDiametro2)))
                                .addComponent(txtResulVolu)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblEsfera)
                        .addGap(43, 43, 43))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEsfera)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRadio2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiametro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiametro2))
                .addGap(18, 18, 18)
                .addComponent(btnVolumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResulVolu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultaVolu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(13, 13, 13)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar1)
                        .addGap(31, 31, 31))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        if (txtBase.getText().isEmpty() || txtAltura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para poder efectuar el calculo debe ingresar un dato ");
        } else {
            Double base = Double.parseDouble(txtBase.getText());
            Double altura = Double.parseDouble(txtAltura.getText());
            Double area = base * altura;
            Double diagonal = Math.sqrt((base * base) + (altura * altura));
            String Area = "" + ((double) Math.round(area * 1000d) / 1000d);
            txtArea.setText(Area);
            String Diagonal = "" + ((double) Math.round(diagonal * 1000d) / 1000d);
            txtDiagonal.setText(Diagonal);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtBaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBaseKeyPressed

        if (evt.getKeyCode() == 10) {
            txtAltura.requestFocus();
        }
    }//GEN-LAST:event_txtBaseKeyPressed

    int cont = 0;
    private void txtBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBaseKeyTyped
        char base = evt.getKeyChar();
        if (Character.isDigit(base) || base == 46) {

        } else {
            evt.consume();
        }

        if (base == 46) {
            cont = cont + 1;
            if (cont > 1) {

                evt.consume();

            }

        }
        if (txtBase.getText().isEmpty()) {
            cont = 0;
        }

    }//GEN-LAST:event_txtBaseKeyTyped

    private void txtBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseActionPerformed

    private void txtAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyPressed
        if (evt.getKeyCode() == 10) {
            btnCalcularActionPerformed(null);
        }
    }//GEN-LAST:event_txtAlturaKeyPressed

    int cont1 = 0;
    private void txtAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyTyped
        char altura = evt.getKeyChar();
        if (Character.isDigit(altura) || altura == 46) {

        } else {
            evt.consume();
        }

        if (altura == 46) {
            cont1 = cont1 + 1;
            if (cont1 > 1) {

                evt.consume();

            }

        }
        if (txtAltura.getText().isEmpty()) {
            cont1 = 0;
        }
    }//GEN-LAST:event_txtAlturaKeyTyped

    private void btnPermietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermietroActionPerformed
        if (txtRadio.getText().isEmpty() && txtDiametro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para poder efectuar el calculo debe ingresar un dato ");
        } else {
            if (flag1 == true) {
                double radio = Double.parseDouble(txtRadio.getText());
                Double resul = (2 * (Math.PI) * (radio));
                String resu = "" + ((double) Math.round(resul * 1000d) / 1000d);
                txtResultadoPeri.setText(resu);
                flag1 = false;
            } else {
                double diametro = Double.parseDouble(txtDiametro.getText());
                Double diam = ((Math.PI) * (diametro));
                String resul2 = "" + ((double) Math.round(diam * 1000d) / 1000d);
                txtResultadoPeri.setText(resul2);
            }

            txtDiametro.setEnabled(true);
            txtRadio.setEnabled(true);
        }
    }//GEN-LAST:event_btnPermietroActionPerformed

    boolean flag1 = false;
    private void txtRadioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadioFocusGained
        txtDiametro.setEnabled(false);
        flag1 = true;
    }//GEN-LAST:event_txtRadioFocusGained

    private void txtDiametroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiametroFocusGained
        txtRadio.setEnabled(false);

    }//GEN-LAST:event_txtDiametroFocusGained

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtDiametro.setText("");
        txtRadio.setText("");
        txtResultadoPeri.setText("");
        txtRadio.setEnabled(true);
        txtDiametro.setEnabled(true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtRadioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadioKeyPressed
        if (evt.getKeyCode() == 10) {
            btnPermietroActionPerformed(null);
        }
    }//GEN-LAST:event_txtRadioKeyPressed

    private void txtDiametroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroKeyPressed
        if (evt.getKeyCode() == 10) {
            btnPermietroActionPerformed(null);
        }
    }//GEN-LAST:event_txtDiametroKeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresar1ActionPerformed
        Opciones op = new Opciones();
        op.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1ActionPerformed

    private void btnLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2ActionPerformed
        txtDiametro2.setText("");
        txtRadio2.setText("");
        txtResulVolu.setText("");
        txtRadio2.setEnabled(true);
        txtDiametro2.setEnabled(true);
    }//GEN-LAST:event_btnLimpiar2ActionPerformed

    private void btnVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumenActionPerformed
        if (txtRadio2.getText().isEmpty() || txtDiametro2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para poder efectuar el calculo debe ingresar un dato ");
        } else {
            if (flag2 == true) {
                double radio2 = Double.parseDouble(txtRadio2.getText());
                Double resul = ((1.33333) * (Math.PI) * (radio2 * radio2 * radio2));
                String resu = "" + ((double) Math.round(resul * 1000d) / 1000d);
                txtResulVolu.setText(resu);
                flag2 = false;
            } else {
                double diam2 = Double.parseDouble(txtDiametro2.getText());
                Double resul = ((0.16666) * (Math.PI) * (diam2 * diam2 * diam2));
                String volu = "" + ((double) Math.round(resul * 1000d) / 1000d);
                txtResulVolu.setText(volu);
            }

            txtDiametro2.setEnabled(true);
            txtRadio2.setEnabled(true);
        }
    }//GEN-LAST:event_btnVolumenActionPerformed

    private void txtDiametro2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametro2KeyPressed
        if (evt.getKeyCode() == 10) {
            btnVolumenActionPerformed(null);
        }
    }//GEN-LAST:event_txtDiametro2KeyPressed

    private void txtDiametro2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiametro2FocusGained
        txtRadio2.setEnabled(false);

    }//GEN-LAST:event_txtDiametro2FocusGained

    private void txtRadio2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadio2KeyPressed
        if (evt.getKeyCode() == 10) {
            btnVolumenActionPerformed(null);
        }
    }//GEN-LAST:event_txtRadio2KeyPressed
    boolean flag2 = false;
    private void txtRadio2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRadio2FocusGained
        txtDiametro2.setEnabled(false);
        flag2 = true;
    }//GEN-LAST:event_txtRadio2FocusGained
    int cont2 = 0;
    private void txtRadio2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadio2KeyTyped
        char radio2 = evt.getKeyChar();
        if (Character.isDigit(radio2) || radio2 == 46) {

        } else {
            evt.consume();
        }

        if (radio2 == 46) {
            cont2 = cont2 + 1;
            if (cont2 > 1) {

                evt.consume();

            }

        }
        if (txtRadio2.getText().isEmpty()) {
            cont2 = 0;
        }
    }//GEN-LAST:event_txtRadio2KeyTyped
    int cont3 = 0;
    private void txtDiametro2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametro2KeyTyped
        char diam2 = evt.getKeyChar();
        if (Character.isDigit(diam2) || diam2 == 46) {

        } else {
            evt.consume();
        }

        if (diam2 == 46) {
            cont3 = cont3 + 1;
            if (cont3 > 1) {

                evt.consume();

            }

        }
        if (txtDiametro2.getText().isEmpty()) {
            cont3 = 0;
        }
    }//GEN-LAST:event_txtDiametro2KeyTyped
    int cont4 = 0;
    private void txtRadioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadioKeyTyped
        char rad = evt.getKeyChar();
        if (Character.isDigit(rad) || rad == 46) {

        } else {
            evt.consume();
        }

        if (rad == 46) {
            cont4 = cont4 + 1;
            if (cont4 > 1) {

                evt.consume();

            }

        }
        if (txtRadio.getText().isEmpty()) {
            cont4 = 0;
        }
    }//GEN-LAST:event_txtRadioKeyTyped
    int cont5 = 0;
    private void txtDiametroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroKeyTyped
        char diam = evt.getKeyChar();
        if (Character.isDigit(diam) || diam == 46) {

        } else {
            evt.consume();
        }

        if (diam == 46) {
            cont5 = cont5 + 1;
            if (cont5 > 1) {

                evt.consume();

            }

        }
        if (txtDiametro.getText().isEmpty()) {
            cont5 = 0;
        }
    }//GEN-LAST:event_txtDiametroKeyTyped
    int cont6 = 0;
    private void txtDiagonalCuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiagonalCuKeyTyped
        char diago = evt.getKeyChar();
        if (Character.isDigit(diago) || diago == 46) {

        } else {
            evt.consume();
        }

        if (diago == 46) {
            cont6 = cont6 + 1;
            if (cont6 > 1) {

                evt.consume();

            }

        }
        if (txtDiagonalCu.getText().isEmpty()) {
            cont6 = 0;
            txtVolumenCu.setText("");
        }
    }//GEN-LAST:event_txtDiagonalCuKeyTyped

    private void txtDiagonalCuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiagonalCuKeyPressed
        if (evt.getKeyCode() == 10) {
            btnCalcularCuboActionPerformed(null);
        }
    }//GEN-LAST:event_txtDiagonalCuKeyPressed

    private void btnCalcularCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCuboActionPerformed
        if (txtDiagonalCu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para poder efectuar el calculo debe ingresar un dato ");
        } else {
            double cubo = Double.parseDouble(txtDiagonalCu.getText());
            double volucubo = (cubo / Math.sqrt(3));
            double volucubo1 = volucubo * volucubo * volucubo;
            String resultado = "" + ((double) Math.round(volucubo1 * 1000d) / 1000d);
            txtVolumenCu.setText(resultado);
        }
    }//GEN-LAST:event_btnCalcularCuboActionPerformed
    int cont7 = 0;
    private void txtDatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatosKeyTyped
        char Datos = evt.getKeyChar();
        if (Character.isDigit(Datos) || Datos == 46) {

        } else {
            evt.consume();
        }

        if (Datos == 46) {
            cont7 = cont7 + 1;
            if (cont7 > 1) {

                evt.consume();

            }

        }
        if (txtDatos.getText().isEmpty()) {
            cont7 = 0;

        }
    }//GEN-LAST:event_txtDatosKeyTyped
    int cont8 = 0;
    private void txtDatosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatosKeyPressed
        if (txtDatos.getText().isEmpty()) {
            
        }else{
            if (evt.getKeyCode() == 10) {
                btnPromedioActionPerformed(null);
                txtDatos.setText("");
                cont8 = cont8 + 1;
                if (cont8<=9) {
                    lblPromedio.setText("Dato " + (cont8+1));
                }
            }
            if (cont8==10) {
            txtDatos.setEnabled(false);
            btnPromedio.setEnabled(false);
        }

        }
    }//GEN-LAST:event_txtDatosKeyPressed
    double Vector[] = new double[10];
    double suma=0;
    int cont9=0;
    private void btnPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromedioActionPerformed
        
        if (txtDatos.getText().isEmpty()) {
          JOptionPane.showMessageDialog(null, "Debe ingresar datos primero");  
        }else{
           if (cont9<10) {
            cont9=cont9+1;
            Vector[cont9-1] = Double.parseDouble(txtDatos.getText());
        }
        txtDatos.setText("");
        txtDatos.requestFocus();
                if (cont9<=9) {
                    lblPromedio.setText("Dato " + (cont9+1));
                }
        if (cont9==10) {
            for (int ite2 = 0; ite2 <10; ite2++) {
                 suma=suma +Vector[ite2];
                 
            }suma=suma/10;
            String meter= ""+((double) Math.round(suma * 10d) / 10d);
            txtPromediado.setText(meter+"");
            txtDatos.setEnabled(false);
            btnPromedio.setEnabled(false);
        } 
        }
    
        
        
    }//GEN-LAST:event_btnPromedioActionPerformed

    private void btnLimpiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar3ActionPerformed
       btnPromedio.setEnabled(true);
       txtDatos.setEnabled(true);
       txtPromediado.setText("");
       txtDatos.setText("");
       txtDatos.requestFocus();
       suma=0;
       cont8=0;
       cont9=0;
       lblPromedio.setText("Dato"+(cont8+1));
       
    }//GEN-LAST:event_btnLimpiar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularCubo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar2;
    private javax.swing.JButton btnLimpiar3;
    private javax.swing.JButton btnPermietro;
    private javax.swing.JButton btnPromedio;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblDiagonal;
    private javax.swing.JLabel lblDiametro2;
    private javax.swing.JLabel lblEsfera;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblRadio2;
    private javax.swing.JLabel lblResultaVolu;
    private javax.swing.JLabel lblResultadoPeri;
    private javax.swing.JLabel lblTitGuia1;
    private javax.swing.JLabel lblVolumenCubo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtDiagonal;
    private javax.swing.JTextField txtDiagonalCu;
    private javax.swing.JTextField txtDiametro;
    private javax.swing.JTextField txtDiametro2;
    private javax.swing.JTextField txtPromediado;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtRadio2;
    private javax.swing.JTextField txtResulVolu;
    private javax.swing.JTextField txtResultadoPeri;
    private javax.swing.JTextField txtVolumenCu;
    // End of variables declaration//GEN-END:variables
}
