package guia5.prograll;


public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuia1 = new javax.swing.JButton();
        btnGuia2 = new javax.swing.JButton();
        btnGuia34 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblOpciones = new javax.swing.JLabel();
        lblImagen2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuia1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnGuia1.setText("App Guia 1");
        btnGuia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuia1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        btnGuia2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnGuia2.setText("App Guia 2");
        btnGuia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuia2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        btnGuia34.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnGuia34.setText("App Guia 3 y 4");
        btnGuia34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuia34ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuia34, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        lblOpciones.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        lblOpciones.setText("Elija una Opcion");
        getContentPane().add(lblOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        lblImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minerva.gif"))); // NOI18N
        lblImagen2.setText("Elija una Opcion");
        getContentPane().add(lblImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 0, 367, 477));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuia34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuia34ActionPerformed
        Guia34 guia34= new Guia34();
        guia34.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGuia34ActionPerformed

    private void btnGuia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuia1ActionPerformed
        Guia1 guia1=new Guia1();
        this.dispose();
        guia1.setVisible(true);
    }//GEN-LAST:event_btnGuia1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuia2ActionPerformed
    Guia2 guia2=new Guia2();
    guia2.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnGuia2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuia1;
    private javax.swing.JButton btnGuia2;
    private javax.swing.JButton btnGuia34;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JLabel lblOpciones;
    // End of variables declaration//GEN-END:variables
}
